### ISSUE TITLE
ReplicateAzureSnapshot.ps1 - Fix for new Storage account security defaults

### ISSUE THREAD

**Issue by chahn1** [JamesKindon/Azure#2]
Microsoft changed the security defaults for storage accounts and public access is no longer allowed by default.  So the script no longer runs without modification. 

https://techcommunity.microsoft.com/t5/azure-storage-blog/azure-storage-updating-some-default-security-settings-on-new/ba-p/3819554

Line 641, need to add -AllowBlobPublicAccess $true

**Comment by JamesKindon** [comment]
Added - thanks for the heads up, has been a little while since I have
looked at this
